spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
  profiles: dev  
---    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qa
    username: root
    password: root 
  profiles: qa 
---
server: 
    port: 9090
---
spring: 
  profiles:
   active: dev      